language: ruby
cache: bundler
rvm:
  - 2.6
addons:
  chrome: stable
before_install:
  - wget https://chromedriver.storage.googleapis.com/81.0.4044.20/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip -d /usr/local/bin
  - gem install bundler
script: bundle exec cucumber
env:
  - TODOMVC_TEST_APP_URL='http://todomvc.com/examples/react/'
  - TODOMVC_TEST_APP_URL='http://todomvc.com/examples/vanillajs/'
