language: ruby
rvm:
  - 2.6
addons:
  chrome: stable
before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 https://www.google.com
  - gem install bundler
script: bundle exec cucumber
env:
  - TODOMVC_TEST_APP_URL='http://todomvc.com/examples/react/'
  - TODOMVC_TEST_APP_URL='http://todomvc.com/examples/vanillajs/'
